# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourismPlaces', '0005_auto_20171211_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourismplace',
            name='description',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
